name: poolinspection
description: A new Flutter project.
version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.10
  flushbar: ^1.10.4
  cupertino_icons: ^0.1.2
  global_configuration: ^1.4.0   
  flutter_spinkit: ^4.1.2 
  mvc_pattern: ^3.6.0
  image_cropper: ^1.3.1
  permission_handler: ^5.0.1+1
  date_format: ^1.0.8
  signature: ^3.1.1
  webview_flutter: 
  open_file: ^3.0.1
  flutter_full_pdf_viewer: ^1.0.4
  flutter_form_builder: 
  strings: ^0.1.2
  intl: 
  image_picker: ^0.6.7+7
  multi_image_picker: ^4.7.12
  dio: ^3.0.8
  rflutter_alert: ^1.0.3
  connectivity: ^0.4.9
  file_picker: ^1.13.3
  path_provider: ^1.6.14
  share_extend: ^1.1.9
  fluttertoast: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/img/app-iconwhite.jpg" 

flutter:
  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/img/app-iconwhite.jpg
    - assets/img/logo.png
    - assets/img/poolsplashimage.png

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/font/Poppins-Regular.ttf
     
  - family: Muli
    fonts:
      - asset: assets/font/Muli-Regular.ttf
        

  - family: AVENIRLTSTD
    fonts:
      - asset: assets/font/AVENIRLTSTD-MEDIUM.OTF
      - asset: assets/font/AVENIRLTSTD-MEDIUMOBLIQUE.OTF
      - asset: assets/font/AVENIRLTSTD-OBLIQUE.OTF
      - asset: assets/font/AVENIRLTSTD-ROMAN.OTF
